import pluginVue from 'eslint-plugin-vue'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import skipFormatting from '@vue/eslint-config-prettier/skip-formatting'

export default defineConfigWithVueTs(
  {
    ignores: ['public/**', 'node_modules/**', 'test/e2e/**', 'tmp/**', 'site/**', 'vendor/*', '!vendor/nibble/', '**/node_modules/**', 'vendor/nibble/frontend/styles/typography.js'],
  },
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  // Inertia pages are addressed by path (e.g. blog/Index), so single-word names are fine there, and their
  // props come straight from Rails in snake_case.
  { files: ['vendor/nibble/frontend/nibble-admin/pages/**/*.vue'], rules: { 'vue/multi-word-component-names': 'off', 'vue/prop-name-casing': 'off' } },
  // shadcn-vue components are generated by its CLI (components.json); keep them as generated.
  {
    files: ['vendor/nibble/frontend/nibble-admin/components/ui/**/*.vue'],
    rules: { 'vue/multi-word-component-names': 'off', 'vue/require-default-prop': 'off' },
  },
  // @nibble components are addressed by their public names (Blocks, Image, ...).
  { files: ['vendor/nibble/frontend/nibble/**/*.vue'], rules: { 'vue/multi-word-component-names': 'off', 'vue/no-v-html': 'off' } },
  // Themes are swappable: they may import only @nibble, @theme, relative paths and their own dependencies.
  {
    files: ['site/themes/**/*.{ts,vue}', 'vendor/nibble/themes/**/*.{ts,vue}'],
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/prop-name-casing': 'off',
      'no-restricted-imports': [
        'error',
        { patterns: [{ group: ['@/*', '~/*', '**/vendor/nibble/frontend/**'], message: 'Themes may only import @nibble, @theme, relative paths and their own dependencies.' }] },
      ],
    },
  },
  // The CP and the app never depend on the active theme; only the shared page resolver loads it.
  {
    files: ['vendor/nibble/frontend/**/*.{ts,vue}'],
    ignores: ['vendor/nibble/frontend/nibble-admin/lib/resolve-page.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [{ group: ['@theme', '@theme/*', '**/themes/**'], message: 'App code must not import theme code.' }] }],
    },
  },
  // Formatting is Prettier's job; ESLint only reports code-quality problems.
  skipFormatting,
)
