// Generated by `bin/rails nibble:schema:types`. Do not edit.
import type { NibbleForm } from '@nibble'
export type EntrySummary = { id: string; type: 'entry'; title: string; uri: string | null; url: string | null; collection: string }
export type TermSummary = { id: string; type: 'term'; title: string; uri: string | null; url: string | null; taxonomy: string }
export type AssetValue = { id: string; title: string; filename: string; kind: string; url: string; alt: string | null; width?: number | null; height?: number | null; srcset?: string | null; focal?: { x: number; y: number } | null }
export type PaginationMeta = { current_page: number; per_page: number; total: number; last_page: number }
export type Paginated<T> = { data: T[]; meta: PaginationMeta }
export interface RecordBase {
  id: number
  uuid: string
  type: 'entry' | 'term'
  blueprint: string
  locale: string
  title: string | null
  slug: string | null
  uri: string | null
  url: string | null
  status: string | null
  published_at: string | null
  updated_at: string | null
  search_snippet?: string
}

export interface PagesPage extends RecordBase {
  collection: 'pages'
  title: string | null
  eyebrow: string | null
  intro: string | null
  blocks: Array<{ id: string; type: string } & Record<string, unknown>>
  seo: { title: string | null; description: string | null; canonical: string | null; og_image: string | null; noindex: boolean; schema_type: string | null; json_ld_overrides: Record<string, unknown> | null }
}

export interface PostsPost extends RecordBase {
  collection: 'posts'
  title: string | null
  excerpt: string | null
  body: string | null
  authors: TermSummary | null
  topics: TermSummary[]
  featured_image: AssetValue | null
  seo: { title: string | null; description: string | null; canonical: string | null; og_image: string | null; noindex: boolean; schema_type: string | null; json_ld_overrides: Record<string, unknown> | null }
}

export interface AuthorsAuthor extends RecordBase {
  taxonomy: 'authors'
  title: string | null
  bio: string | null
  website: string | null
}

export interface TopicsTopic extends RecordBase {
  taxonomy: 'topics'
  title: string | null
  description: string | null
}

export interface SeoGlobals {
  title_template: string | null
  default_description: string | null
  default_share_image: AssetValue | null
  organization_name: string | null
  organization_logo: AssetValue | null
  verification_tags: Array<Record<string, unknown> & { id: string }>
}

export interface SiteGlobals {
  name: string | null
  tagline: string | null
  logo: AssetValue | null
  favicon: AssetValue | null
  contact_email: string | null
  social_links: Array<Record<string, unknown> & { id: string }>
}

export interface ViewProps {
  'about': {
    authors: (AuthorsAuthor)[]
    contact: NibbleForm
  }
  'authors/show': {
    posts: Paginated<(PostsPost)>
  }
  'home': {
    featured: (PostsPost)[]
    recent: (PostsPost)[]
    topics: Pick<(TopicsTopic), 'title' | 'uri' | 'id' | 'type' | 'url'>[]
  }
  'posts/index': {
    posts: Paginated<(PostsPost)>
  }
  'posts/show': {
    related: (PostsPost)[]
  }
  'search': {
    results: Paginated<(PagesPage | PostsPost)>
  }
  'topics/index': {
    topics: (TopicsTopic)[]
  }
  'topics/show': {
    posts: Paginated<(PostsPost)>
  }
}
