module Nibble
  class TypeGenerator
    PRELUDE = <<~TS.freeze
      // Generated by `bin/rails nibble:schema:types`. Do not edit.
      import type { NibbleForm } from '@nibble'
      export type EntrySummary = { id: string; type: 'entry'; title: string; uri: string | null; url: string | null; collection: string }
      export type TermSummary = { id: string; type: 'term'; title: string; uri: string | null; url: string | null; taxonomy: string }
      export type AssetValue = { id: string; title: string; filename: string; kind: string; url: string; alt: string | null; width?: number | null; height?: number | null; srcset?: string | null; focal?: { x: number; y: number } | null }
      export type PaginationMeta = { current_page: number; per_page: number; total: number; last_page: number }
      export type Paginated<T> = { data: T[]; meta: PaginationMeta }
      export interface RecordBase {
        id: number
        uuid: string
        type: 'entry' | 'term'
        blueprint: string
        locale: string
        title: string | null
        slug: string | null
        uri: string | null
        url: string | null
        status: string | null
        published_at: string | null
        updated_at: string | null
        search_snippet?: string
      }
    TS

    def self.theme_output(config = Nibble.config) = config.theme_path&.join(".nibble", "types.d.ts")

    # An unchanged file is left alone: rewriting it would have Vite reload every open page for nothing.
    def self.write!(schema = Nibble.schema, config: Nibble.config)
      output = theme_output(config) or return nil
      types = new(schema, config:).generate
      return output if output.file? && output.read == types

      output.dirname.mkpath
      output.write(types)
      output
    end

    def initialize(schema = Nibble.schema, config: Nibble.config)
      @schema = schema
      @config = config
    end

    def generate
      blocks = [ PRELUDE ]
      (@schema.collections + @schema.taxonomies).each do |parent|
        scope = parent.kind == "collections" ? "collection: '#{parent.handle}'" : "taxonomy: '#{parent.handle}'"
        @schema.blueprints_for(parent).each do |item|
          blocks << interface("#{pascal(parent.handle)}#{pascal(item.handle)}", Blueprint.new(item, schema: @schema).fields, extends: "RecordBase", extra: [ scope ])
        end
      end
      @schema.globals.reject { |item| item.handle == Integrations::HANDLE }.each do |item|
        inline = Schema::Item.new(kind: "blueprints", handle: item.handle, parent: item.key, path: item.path, layer: item.layer, data: item["blueprint"])
        blocks << interface("#{pascal(item.handle)}Globals", Blueprint.new(inline, schema: @schema).fields)
      end
      blocks << view_props if @config.theme_path
      blocks.join("\n")
    end

    private

    def interface(name, fields, extends: nil, extra: [])
      members = extra + fields.select(&:api?).map { |field| "#{field.handle}: #{field.fieldtype.ts_type}" }
      "export interface #{name}#{" extends #{extends}" if extends} {\n#{members.map { |member| "  #{member}" }.join("\n")}\n}\n"
    end

    def view_props
      views = Views.sidecars(config: @config).map do |sidecar|
        props = sidecar.queries.map do |prop, raw|
          spec = Query::Spec.parse(raw, schema: @schema)
          next "    #{prop}: NibbleForm" if spec.source.form?

          record = record_type(spec)
          record = "Pick<#{record}, #{(spec.fields | %w[id type title uri url]).map { |field| "'#{field}'" }.join(' | ')}>" if spec.fields && !spec.source.search?
          "    #{prop}: #{spec.paginate ? "Paginated<#{record}>" : "#{record}[]"}"
        end
        "  '#{sidecar.view}': {\n#{props.join("\n")}\n  }"
      end
      "export interface ViewProps {\n#{views.join("\n")}\n}\n"
    end

    def record_type(spec)
      source = spec.source
      parents = if source.search?
        definition = Search.indexes(schema: @schema)[source.handle].to_h
        Array(definition["collections"]).filter_map { |handle| @schema.collection(handle) } + Array(definition["taxonomies"]).filter_map { |handle| @schema.taxonomy(handle) }
      else
        [ source.schema_item(@schema) ]
      end
      names = parents.flat_map { |parent| @schema.blueprints_for(parent).map { |item| "#{pascal(parent.handle)}#{pascal(item.handle)}" } }
      names.empty? ? "RecordBase" : "(#{names.join(' | ')})"
    end

    def pascal(handle) = handle.to_s.delete_prefix("nibble::").camelize
  end
end
